// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wjpzjlifxavhjfichskp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqcHpqbGlmeGF2aGpmaWNoc2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTE1MzAsImV4cCI6MjA2ODgyNzUzMH0.OmW6wj_O5TGn54m4mg3PcHWBt79Djhc1jpmQgcTAH84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});